ktor:
    application:
        modules:
            - com.example.ApplicationKt.module
    deployment:
        port: $PORT
postgres:
  url: $DB_URL
  user: $DB_USERNAME
  password: DB_PASSWORD
jwt:
  secret: $JWT_SECRET